#**************** Set site global variables ****************
# Setup
title:               Pathway Guide
description:         'An online textbook for pathway understanding'
baseurl:             /guide
domain:              'http://pathwaycommons.github.io'

# About/contact
author:
  name:              Pathway Commons
  url:               http://www.pathwaycommons.org/

# Custom vars
version:             0.1.0
branch: gh-pages

# Declare the path relative to <source> for media and static items
media_root:          media
static_root:         public
src_root:            src
site_root:           _site

exclude:
  - src
  - docs
  - build.R
  - Gemfile
  - README.md
  - atom
#**************** Override defaults ****************

# Plugins
plugins: [jekyll-watch, jekyll_github_sample]

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false

collections:
  case_studies:
    output: true
    description: Case Studies

  presentations:
    output: true
    description: Presentations

  primers:
    output: true
    description: Primers

  workflows:
    output: true
    description: Workflows
