#**************** Set site global variables ****************
# Setup
title:               Guide
tagline:             'Training Resources'
description:         'Guide'
baseurl:             '/guide'

# About/contact
author:
  name:              Pathway Commons
  url:               https://twitter.com/PathwayCommons
  email:             https://groups.google.com/forum/#!forum/pathway-commons-help

# Custom vars
version:             1.0.0
branch: gh-pages

# Declare the path relative to <source> for media and static items
media_root:          media
static_root:         public
src_root:            src
site_root:           _site

exclude:
  - src
  - docs
  - build.R
  - Gemfile
  - README.md
  - atom
#**************** Override defaults ****************

# Plugins
gems:                [jekyll-watch]

# Outputting
# post permalink style 'pretty' (/:categories/:year/:month/:day/:title/)
permalink:     pretty

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false

collections:
  case_studies:
    output: true
    permalink: /case_studies/:path/
    layout: document
    index: /case_studies/archive/
    description: Deep-dive into pathway analysis
    icon: index/case_study.png

  reading_list:
    output: true
    permalink: /reading_list/:path/
    layout: reading_list
    index: /reading_list/archive/
    description: Curated article sets
    icon: index/reading_list.png

  datasets:
    output: true
    permalink: /datasets/:path/
    layout: datasets
    index: /datasets/archive/
    description: Datasets
    icon: index/datasets.png

  communications:
    output: true
    permalink: /communications/:path/
    layout: page
    index: /communications/archive/
    description: Communications
    icon: index/documents.png

  primers:
    output: true
    permalink: /primers/:path/
    layout: primers
    index: /primers/archive/
    description: Primers
    icon: index/primers.png

  # workflows:
  #   output: true
  #   permalink: /workflows/:path/
  #   layout: workflows
  #   index: /workflows/archive/
  #   description: Workflows
  #   icon: index/workflows.png
