#**************** Set site global variables ****************
# Setup
title:               Guide
tagline:
  text: Pathway Commons
  link: http://www.pathwaycommons.org/
description:         'Guide'
baseurl:             /guide
domain:              'http://pathwaycommons.github.io'

# About/contact
author:
  name:              Pathway Commons
  url:               https://twitter.com/PathwayCommons
  email:             https://groups.google.com/forum/#!forum/pathway-commons-help

# Custom vars
version:             0.1.0
branch: gh-pages

# Declare the path relative to <source> for media and static items
media_root:          media
static_root:         public
src_root:            src
site_root:           _site

exclude:
  - src
  - docs
  - build.R
  - Gemfile
  - README.md
  - atom
#**************** Override defaults ****************

# Plugins
plugins: [jekyll-watch, jekyll_github_sample]

# Outputting
# post permalink style 'pretty' (/:categories/:year/:month/:day/:title/)
permalink: pretty

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false

collections:
  case_studies:
    output: true
    permalink: /case_studies/:path/
    index: /case_studies/archive/
    description: Case Studies

  presentations:
    output: true
    permalink: /presentations/:path/
    index: /presentations/archive/
    description: Presentations

  primers:
    output: true
    permalink: /primers/:path/
    index: /primers/archive/
    description: Primers

  workflows:
    output: true
    permalink: /workflows/:path/
    index: /workflows/archive/
    description: Workflows
