---
title: Pathway Enrichment - I
subtitle: Use ovarian cancer RNA sequencing data to identify altered pathways with Gene Set Enrichment Analysis and visualize using an Enrichment Map.
cover: cover.jpg
date: 2016-10-24
layout: embedded_wrapper
category: Enrichment Analysis
badges:
  - RNA-Seq
  - R
  - Ovarian Cancer
  - Intermediate
---

> Analyze high-grade ovarian cancer expression data generated by The Cancer Genome Atlas for pathways altered between expression subtypes. You will source RNA sequencing data from the Genomic Data Commons repository, compare expression between two ovarian subtypes and analyze the expression results for enriched pathways. Finally, our list of enriched pathways is displayed as an enrichment map which organizes pathways by larger themes.

{% assign docs = (site.workflows | where: 'group','pathway_enrichment_gdc' | sort: 'order' ) %}

<div class="progress-tracker-wrapper">
  {% include progress_tracker.html %}
  <div id="progress-tracker-content"></div>
</div>
